basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('account/', include('account.urls', namespace='account')),
    # path('orders/', include('orders.urls', namespace='orders')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name= 'store'

urlpatterns=[
    path('rate/<slug:slug>', views.Rate, name='rate'),
    path('test', views.test, name='rate'),
    path('', views.product_all, name='product_all'), #home view with all products
    path('<slug:slug>', views.product_detail, name='product_detail'),#detailed view of all products
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'), #this is the filte by category ex. keto
]

store/models.py
from django.conf import settings
from django.db import models
User = settings.AUTH_USER_MODEL
from django.urls import reverse #allows us to build a url
#The following is our tables that will be used in the database
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)
        
class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True) # slug for category models  in django.db import models class behind the url you can type/admin

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])
        
    def __str__(self):
        return self.name # thunderer for backwards compatibility

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator') #who is this product creator record
    title = models.CharField(max_length=255) # title for product
    author = models.CharField(max_length=255, default='admin') #category of sproduct
    description= models.TextField(blank=True) #discription of the product
    image = models.ImageField(upload_to='images/', default = 'images/default.png') #upload img and allow us to upload 
    slug = models.SlugField(max_length=255, unique=True) #
    price = models.DecimalField(max_digits=4, decimal_places=2)
    vegan = models.BooleanField(default=True)
    keto= models.BooleanField (default=True)
    lowCarb= models.BooleanField (default=True) #manages stock of product stock or out of stock
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)#used when we add a product
    updated = models.DateTimeField(auto_now=True)#used when we update a product and we want record
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'#how we want to order products and details
        ordering = ('-created',)

    #builds url to view prod details on click   
    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])


    def __str__(self):
        return self.title # thunderer method


class Review(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    product = models.ForeignKey(Product, models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=3000, blank=True)
    rate = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id) 

store/views.py
from django.shortcuts import get_object_or_404, redirect, render

from .models import Category, Product, Review


def product_all(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    reviews = Review.objects.filter(product=product).order_by('-id')
    print (reviews)
    return render(request, 'store/products/single.html', {'product': product, 'reviews': reviews})

def test(request):
    return "Hello there"

def Rate(request, slug):
    if request.method == "POST":        
        print("saving", slug)
        product = get_object_or_404(Product, slug=slug, in_stock=True)
        subject = request.POST.get('subject')
        review = request.POST.get('review')
        rate = request.POST.get('rate')
        user = request.user
        Review(user=user, product=product, subject=subject, review=review, rate=rate).save()
        return redirect('/' + slug) 

templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="container">
    <div class="row">
      <div class="album py-5">


        <div class="pb-3"><h1 class="h3">Meals</h1></div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}<!--for loop that will -->

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">£{{product.price}}</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/store/products/single.html
{% extends "store/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}


<!-- Product Detail -->
<div class="small-container single-product">
    <div class="row g-3">
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-info-circle me-2"
        viewBox="0 0 16 16"><path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
        <path
          d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
      </svg> FOOD ALLERGY WARNING! Please read discription before purchasing this product.
    </div>
    <div class="row"> 
        <div class="col-1">
            <img src="{{ product.image.url }}">
        </div>
        <div class="col-21">
            <p>KETO</p>
            <h1>{{ product.title }}</h1>
            <div class="price"><span class="h4 fw-bold">${{ product.price }}</span></div>
            <label for="select">Qty</label>
                                <select id="select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                </select>
                                <div class="add-to-basket">
                                    <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success btn-sm">Add to basket</button>
                                    <button type="button" id="add-button" value="{{product.id}}" class="btn btn-light fw500">Add to Favorites</button>
                                </div>
        </div>
        <div class="col-22">
            <h3>Details</h3>
            <p>Cajun Roast chicken baked on a bed of potatoes and vegetables.</p>
            <h3>Ingredients</h3>
            <p>{{ product.description|slice:":500" }}...</p>
        </div>
        </div>
    </div>
</div>

<!-- Reviews -->
<div class="container mt-5">
    <h5 class="text-uppercase font-weight-bold">Customer Reviews</h5>
    <hr class="mt-0 pt-0">
    <div class="row">
        <div class="col-sm-7 mt-2">
            {% for review in reviews %}
            <div class="review-heading">
                <a><i>{{ review.user }}</i></a>
                <br>
                <a><i></i>{{ review.subject }}</a>
                <a class="m1-2"><i class="far fa-clock mr-1"></i>{{ review.created_at }}</a>
            </div>
            <div class="review-body mt-2">
                <p>{{ review.review }}</p>
            </div>
            {% endfor %}
        </div>
        <div class="col-sm-5 mt-2">
            <form class="col s12" method="POST" action='rate/{{product.slug }}' role="form">
                {% csrf_token %}       
                <label>How do you rate this meal?</label>
                    <div class="rate">
                        <input type="radio" name="rate" id="rating10" value="5" required><label for="rating10" title="5"></label>
                        <input type="radio" name="rate" id="rating9" value="4.5" required><label for="rating9" title="4.5" class="half"></label>
                        <input type="radio" name="rate" id="rating8" value="4" required><label for="rating8" title="4"></label>
                        <input type="radio" name="rate" id="rating7" value="3.5" required><label for="rating7" title="3.5" class="half"></label>
                        <input type="radio" name="rate" id="rating6" value="3" required><label for="rating6" title="3"></label>
                        <input type="radio" name="rate" id="rating5" value="2.5" required><label for="rating5" title="2.5" class="half"></label>
                        <input type="radio" name="rate" id="rating4" value="2" required><label for="rating4" title="2"></label>
                        <input type="radio" name="rate" id="rating3" value="1.5" required><label for="rating3" title="1.5" class="half"></label>
                        <input type="radio" name="rate" id="rating2" value="1" required><label for="rating2" title="1"></label>
                        <input type="radio" name="rate" id="rating1" value="0.5" required><label for="rating1" title="0.5" class="half"></label>
                    </div>

                    <input type="text" class="form-control" name="subject" placeholder="Subject">
                    <br>
                    <textarea name="review" rows="4" class="form-control" placeholder="Write Your Review"></textarea>
                    <br>
                    <input type="submit" value="Submit Review" class="btn btn-danger btn-md m-0" >
                    <br>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Product Detail Style -->
<style>
.row{
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
    padding-left: 70px;
    padding-right: 70px;
}
.single-product{
    margin-top: auto;
}
.single-product .col-1{
    display: flex;
    align-items: center;
    justify-content: space-around;
}
.single-product .col-1 img{
    height: 60%;
}
.col-1{
    display: flex;
    align-items: center;
    justify-content: space-between;
}
.single-product .col-21{
    text-align: center;
    padding: 40px 20px;
    margin: 20px;
    box-shadow: 0 0 20px 0px rgba(0,0,0,0.1);
}
.single-product .col-22{
    text-align: center;
    padding: 40px 20px;
    box-shadow: 0 0 20px 0px rgba(0,0,0,0.1);
}

.col-21{
    padding-left: 50px;
    padding-right: 500px;
}
.col-21 input{
    text-align: center;
    max-width: 41px;
    margin: 10px;
}
.col-21 h1{
    font-size: 32px;
    margin: 24px 0;
    color: #555;
}
.col-21 p{
    font-size: 20px;
    padding: 0px;
    color: #555;
}
.col-21 h4{
    font-weight: 400;
    font-size: 20px;
    padding: 0px;
    color: #555;
}
.col-22 p{
    font-size: 12px;
    margin: 12px 0;
    color: #777;
}
.col-22 h3{
    font-weight: 600;
    color: #555;
    font-size: 18px;
    margin-top: 15px;
}
.price{
    margin-bottom: 10px;
}
.add-to-basket{
    margin-top: 13px;
}

/* Rating */
.rate > input{
    display: none;
}
.rate{
    margin-bottom: 2.5rem;
    border: 0;
}
.rate > label{
    float: right;
}
.rate > label:before{
    display: inline-block;
    font-size: 1.1rem;
    font-family: FontAwesome;
    content: "\f005";
    margin: 0;
    padding: 0.3rem .2rem;
    cursor: pointer;
}
.rate .half:before{
    content: "\f089";
    position: absolute;
    padding-right: 0;
}
input:checked ~ label, label:hover ~ label{
    color: #ffb503;
}
input:checked + label:hover, input:checked ~ label:hover, input:checked ~ label:hover ~ label, label:hover ~ input:checked ~ label{
    color: #cc9000;
}

</style>



<!--ajax request to add product to basket using the button. this will bring data from the DB to the front-->
<script> 
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })



</script>
{% endblock %} 